# Custom Language File for Launcher Customizer

[ejs.app]
title = "AzurRP Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://azur-rp.eu/link/discord"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR AZUR"
welcomeDescription = ""
welcomeDescCTA = "Vous n'Ãªtes qu'a quelques cliques de Azur."
